### ISSUE TITLE
WFS Editing

### ISSUE THREAD

**Issue by am2222** [sothawo/mapjfx#34]
Hi,
is it possible to handle wfs editing using mapjfx?

**Comment by sothawo** [comment]
just had a short look at what this is. Technically it would be possible, although quit some work. 

First it would be necessary to add the possibility to add addition WFS layers to a map. This should be no big problem, as this would be basically a setup/configuration of an additional vector source for the map, optionally with a on/off check.

Editing is quite something different. Here one needs to specify what and how should be edited; this first must be implemented in the JavaScript layer and then it would be necessary to define the Java methods needed to achieve this and to implement the Java part and the connetion between the JavaScript and Java parts.

I do not know what parts can/should be edited - I am not a geographic man - but I think this would be different for each application that might use mapjfx to do this. So as a library mapjfx could only implement the basic common operations. What might these be?

So from the technical point of view it should be possible. Can I do it? From the technical point of view yes. From the time I have - this is a hobby project I have - rather no.

And as the rumour goes that JavaFX will not be included in the Oracle JDK from version 11 on, it will be hard to decide how to go along anyway, because having an independent JFX means that in future tests are needed to support a given version JDK with some JFX implementation.

So I won't actively start implementing this, if somebody wants to contribute, she/he is very welcome.

**Comment by am2222** [comment]
@sothawo thanks for your detailed answer, can you please give me some hints about possible alternatives for javafx?I think this one is much more powerful than others
