### ISSUE TITLE
increase performance

### ISSUE THREAD

**Issue by am2222** [sothawo/mapjfx#41]
Hi,
Is there any method to increase maps performance?
I have added some of my own functions to manage wfs layers but it is really laggy.

**Comment by sothawo** [comment]
hard to say without seeing code changes. Did you add changes to the Javascript part or the java part? If the Javascript part, how is it working in the mapview-local.html file (in src/main/rsesources)?

**Comment by am2222** [comment]
@sothawo Well it is a bit hard to share the code, I'll try to share it after some cleaning. The new changes are mostly in javascript part (I am adding wfs editting into map) and it is laggy when a wfs layer is added into map. 
In mapview-local.html it works perfect. without any lags but when It comes to load into webview it is laggy. Is there any way to increase memory usage by webview? it may fix this issue.

**Comment by am2222** [comment]
what about using other webview components such as https://www.teamdev.com/jxbrowser, does it makes any differences?

**Comment by sothawo** [comment]
so the culprit is probably the Webkit browser used by the WebEngine.
First I wanted to use just the plain components that are included in Java8 (this will change in 11 anyway, when JavaFX is no longer bundled). 
Second, a jxbrowser license costs 1.500€, an opensource license would mean that mapjfx "Cannot be used for a commercial purpose;", a restrictio I do not want to put on my library.

About memory for the Webview: As far as I know there is no special setting, the only thing that might help is increasing the memory for the whole application.

**Comment by am2222** [comment]
thanks very much so the only way is to increase whole apps memory?why the performance is poor when we want to work with vectors?is it normal even?

**Comment by sothawo** [comment]
I am not sure if more memory for the app will increase the memory the browser uses for javascript.

**Comment by am2222** [comment]
@sothawo I am trying to usin jxbrowser I'll report the results.

**Comment by am2222** [comment]
@sothawo well in first tries the performance is quite good and it looks like what I expected.
