### ISSUE TITLE
The OfflineCache is Caching my RestFul API

### ISSUE THREAD

**Issue by oosam2** [sothawo/mapjfx#68]
Hi

I get problem when I use OfflineCache 😢

I have spring boot restful api server, the request work fine but the response I get the cache of my restful from your OfflineCache.

when I comment Offline Cache it work fine.

example of restful cache file name "http%3A%2F%2Flocalhost%2Flogin%2Fauthorize%2F"
it like "http://localhost/login/authorize/"   <== my api   😢

Thanks for this wondrful library.
✌😁🌹

**Comment by sothawo** [comment]
In order to do the offline caching, mapjfx needs to intercept all the network calls, there is no way to only intercept the calls from the mapjfx component.

The `OfflineCache` class has a method `setNoCacheFilters(List<String>)`. With this method you can set a list of Strings - which will be compiled to `java.util.regex.Pattern`s - for which the caching is disabled. Any URL that matches one of these patterns will not be cached.

Currently you can only set patterns for URLS that should **not** be cached.

**Comment by oosam2** [comment]
thanks for replay

I will use setNoCacheFilters(List<String>) 

but, can you make method that is opposite of setNoCacheFilters(List<String>)

because you we can handle map url better than handle all other urls

also, I don't know if that intercept WebView or not

🌹

**Comment by sothawo** [comment]
put that in issue #69

**Comment by sothawo** [comment]
implemented in 2.10.2 and 1.29.2, `OfflineCache` now has a method `setCacheFilters(List<String>)` which defines what to cache.
