### ISSUE TITLE
Any way to accurately define the displayed area?

### ISSUE THREAD

**Issue by Yaldabaoth64** [sothawo/mapjfx#91]
Hello,
first, thanks for this library, it helped me alot.

Now, my question.
Im trying to synchronize a graph in front of the mapview, to better display information. So that means that any point in latlong on my graph, should be the same on the mapView. Right now, im using "setExtend()" to display the correct part of the map that fits the displayed area on my graph. Sadly this way will always give me a map section that is slightly bigger than what i want. 

Is there a way to define an exact rectangle of what should be displayed with two latlongs (for example bottom left and top right), that doesnt try to "fit" the coordinates and make the displayed section bigger?

Thanks alot!

**Comment by sothawo** [comment]
Just been playing around with the mapjfx-demo app and the test app from the mapjfx project itself. When I set an extent there, this works. 
Of course you may have areas outside of your defined extent that are displayed, when the aspect ratio of the extent the the window don't match. Let's say, your extent is a square, having an AR of 1:1, but the window is a rectangle with AR 2:1 (width = 2*height). Then when setting the extent you will end up with the whole square of the extent fitting the window, but on the left and right there are additional areas visible. setExtent(Extent) fits the map so that the whole extent is visible.

If you want to restrict your map in this case, so the the left and right borders of the extent fit the left and right borders of the window, then you should use constrainExtent(Extent). But this leads to areas of the extent at the top/bottom not being visible (and you could not move/pan outside of the constrained area.

When you set an extent and see a bigger area, is this on all 4 sides or just either on top/bottom or left/right?

**Comment by Yaldabaoth64** [comment]
Thanks for the answer. Yes the part that is bigger is always left and right.

After some tests with forcing a visible square on the map i realized why the map will always be wider than high. Depending on how close the visible area is to the poles, the distance between latitudes will shrink. So displaying a visible square in the middle of europe will result in a (sort of) rectangle of latitude/longitude area.

The library is working correctly, my understanding of the displayed area was wrong.

Im now using this factor to correct my displayed longitude areas.:
Math.cos(latitude * Math.PI/180.0) / 1.11120), with latitude beeing the latitude of the center of the displayed area. 

Sadly even with this, the displayed area is still a bit off of what i want to display, because the displayed area isnt really a rectangle, but more curved trapezoid.

Is there a way to get the new range of displayed latitude/longitude after a map change? Like a dataset of latitude/longitude ranges that are currently visible? Calculating all of that in my graph and displaying that range through a two coordinates extent will always be slightly off. It would be much easier to get the new displayed area from the webview and fit my graph accordingly.

Thanks for testing out the displayed area, even if the problem wasnt really with your library, but more with my misunderstanding how maps work.

**Comment by sothawo** [comment]
you can register for the MAP_BOUNDING_EXTENT event, this should come in, when the map has changed, see the demo app https://github.com/sothawo/mapjfx-demo/blob/main/src/main/java/com/sothawo/mapjfxdemo/Controller.java#L505-L509

**Comment by Yaldabaoth64** [comment]
With this i was able to fix my view. For testing purposes i tried displaying a point, and it tracks the map perfectly. Thanks for that.
